#!/usr/bin/env node

'use strict'

var util = require('../index.js')

var identity = util.createIdentity()
var secret = util.createSecret()

util.createQrImageWithSecret(identity, secret, 'qr.png')

console.log('IDENTITY')

console.log(identity)

console.log('SECRET')

console.log(secret)

console.log('QR CODE IN qr.png file')
